### ISSUE TITLE
[Bug] After turning on encryption tags and headers are available only for public notes

### ISSUE THREAD

**Issue by SemyonSinchenko** [Artawower/orgnote#10]
### Thank you for the bug report

- [X] I am using the latest version of the `OrgNote` app.
- [X] I already checked other related issues
- [X] I have read the [WIKI](https://github.com/Artawower/orgnote/wiki)

### Bug description and steps to reproduce

Graph:

![image](https://github.com/Artawower/orgnote/assets/29755009/18683308-de8b-4ec6-8e4e-31a349b8d8fc)
Home:

![image](https://github.com/Artawower/orgnote/assets/29755009/f72b7cec-7637-4286-9f6a-208ac266c559)

If I open a note, everything is clear and rendered correctly. It looks like tags/titles are unavailable in graph-view and home only.

### Debug info

OrgNote: 0.17.0
Language: en-US

Screen:
  Screen resolution: 1536x864
  Screen color depth: 24
  Device pixel ratio: 1.25

Encryption:
  Type: gpgPassword
  Password provided: true

Env:
  API URL: https://org-note.com/api/v1/
  AUTH URL: https://org-note.com
  MODE: production

Quasar info:
  edg: true
  version: 123.0.0.0
  versionNumber: 123
  win: true
  desktop: true
  edgeChromium: true
  name: edgechromium
  platform: win
 standalone: false

**Comment by SemyonSinchenko** [comment]
The same problem appears on Android.

**Comment by Artawower** [comment]
Should work after the latest release. The only thing is that already synchronized notes will not have meta properties. To make them appear you will need to re-login or pre-clear the data on the client, after the next synchronization meta information should be correctly decrypted.

**Comment by SemyonSinchenko** [comment]
It works!
