### ISSUE TITLE
[Bug] Inline code highlighting not working in list

### ISSUE THREAD

**Issue by SemyonSinchenko** [Artawower/orgnote#14]
### Thank you for the bug report

- [X] I am using the latest version of the `OrgNote` app.
- [X] I already checked other related issues
- [X] I have read the [WIKI](https://github.com/Artawower/orgnote/wiki)

### Bug description and steps to reproduce

That is how the note looks in web:
![image](https://github.com/user-attachments/assets/478ddd34-4aec-487e-9375-d7c7a070dc3d)
And that is how it looks in emacs:
![image](https://github.com/user-attachments/assets/cbf963da-9548-4585-8a27-ab551c1b4b95)

So, it looks like code highlighting is not working in the case it is in the list.
Overall inline code highlighting works well:
![image](https://github.com/user-attachments/assets/27ae6b09-7b77-4046-9639-9a582f831f71)

### Debug info

```
OrgNote: 0.21.7
Language: en-US

Screen:
  Screen resolution: 1920x1200
  Screen color depth: 24
  Device pixel ratio: 1.25

Encryption:
  Type: gpgPassword
  Password provided: true

Env:
  API URL: https://org-note.com/api/v1/
  AUTH URL: 
  MODE: production

Quasar info:
  chrome: true
  version: 127.0.0.0
  versionNumber: 127
  linux: true
  desktop: true
  webkit: true
  name: chrome
  platform: linux
 standalone: false
```

### Additional context

I tried both `~` and `=` symbols to mark inline code

**Comment by Artawower** [comment]
The real reason was not the list, it was due to the table delimiter character - `|`.

The latest version (0.21.8) should contain a fix for this problem.

**Comment by SemyonSinchenko** [comment]
Thanks a lot! I updated the version and everything works fine from now!
![image](https://github.com/user-attachments/assets/e6c7eb06-34fb-489e-a211-931fbd9702cc)
