### ISSUE TITLE
[Feature request] Make orgnote-cli error messages more verbose

### ISSUE THREAD

**Issue by SemyonSinchenko** [Artawower/orgnote#27]
**Is your feature request related to a problem? Please describe.**
At the moment if I make a mistake in args or commands of the orgnote-cli, it may be very hard to realize what is the problem based on the text of the error message.

An example:
```sh
[sem@toolbox ORG]$ orgnote-cli --debug --sync --force
2024-11-04T09:46:23.718Z-warn: info.message
warn: Force sync enabled. All cache will be cleared.
2024-11-04T09:46:23.721Z-info: info.message
info: Current configuration: {
  remoteAddress: 'https://org-note.com/api/v1',
  token: '***',
  rootFolder: '/var/home/sem/Nextcloud/ORG/orgnote',
  version: 'v1',
  logPath: '~/var/logs/orgnote.log',
  backupCount: 2,
  name: 'Main',
  backupDir: '/var/home/sem/Nextcloud/Backup/Orgnote',
  encrypt: 'gpgPassword',
  gpgPassword: '***',
  _: [ [length]: 0 ],
  debug: true,
  sync: true,
  force: true,
  '$0': '/usr/local/bin/orgnote-cli'
}
[line 64]: LOG FILE ALREADY EXISTS ~/var/logs/orgnote.log
2024-11-04T09:46:23.722Z-error: info.message
error: Unexpected error: 'Command undefined is not supported'
node:fs:2368
    return binding.writeFileUtf8(
                   ^
                                                                                                                                                                           
Error: ENOENT: no such file or directory, open '~/var/logs/orgnote.log'
    at writeFileSync (node:fs:2368:20)
    at file:///usr/local/lib/node_modules/orgnote-cli/dist/index.js:115646:43 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/var/logs/orgnote.log'
}
```

while the real reason of the error is that the command should be `orgnote-cli sync --debug --force`

**Describe the solution you'd like**
In the case I typed a wrong command or passed a wrong argument to the cli I would like to see an error that at least indicates it. For example, it may look like this:

```sh
[sem@toolbox ORG]$ orgnote-cli --debug --sync --force
Error: unknown argument "--sync", did you mean "orgnote-cli sync"?
```

**Describe alternatives you've considered**
.

**Additional context**
Minor issue.

**Comment by Artawower** [comment]
I have updated orgnote-cli to version 0.12.3.
I tried to improve logging, added correct version output, and also replaced the library for executing CLI commands, the new library should have better typo hints. 
Or, if the command is very different, `--help` will be output.
