### ISSUE TITLE
Style guide is missing

### ISSUE THREAD

**Issue by shmwot** [Artawower/orgnote#28]
Pretty much the title, please do add a style guide because this looks like a project I definitely wanna contribute to.
Thanks!

**Comment by Artawower** [comment]
An early version of the contribution guide is available on the [wiki](https://github.com/Artawower/orgnote/wiki/Contribution-guide), it will definitely still be updated. So let me know what you think about it

**Comment by shmwot** [comment]
looks pretty good so far! Thank you!
